### ISSUE TITLE
请教下这个是用什么工具生成的？

### ISSUE THREAD

**Issue by xiaoyierle** [lynnandtonic/a-single-div#29]
您好，请问这些是用工具生成的吗？还是一点一点写出来的？

**Comment by xiaoyierle** [comment]
> Hello! I translated this with Google translate so hopefully I have it right.
> 
> I don’t use a tool to generate these illustrations. I write the CSS by hand.

Hello! I translated this with Google translate so hopefully I have it right.

I saw an example on your website. My screenshot shows that there are a lot of positioning attributes and color settings. I feel that the workload of these drawings is very large. How do you manage these positionings accurately?

**Comment by xiaoyierle** [comment]
> Hello! I translated this with Google translate so hopefully I have it right.
> 
> I don’t use a tool to generate these illustrations. I write the CSS by hand.

I saw an example on your website. My screenshot shows that there are a lot of positioning attributes and color settings. I feel that the workload of these drawings is very large. How do you manage these positionings accurately?
![image](https://user-images.githubusercontent.com/24968758/112759655-994c3f00-9026-11eb-82d3-a08e161190d4.png)

**Comment by bilibiliou** [comment]
> Hello! I translated this with Google translate so hopefully I have it right.
> 
> I don’t use a tool to generate these illustrations. I write the CSS by hand.

amazing perseverance, awesome !!!


star and follow NOW

**Comment by lynnandtonic** [comment]
Thank you! 

For some of the more complicated ones, I add comments so I can organize the layers. https://github.com/lynnandtonic/a-single-div/blob/main/_styl/entries/alamo.styl#L20-L32

It can be difficult to manage sometimes, though!

**Comment by bilibiliou** [comment]
You can really code css !
